<a href="https://colab.research.google.com/github/barabud/tugas1/blob/main/Preprocessing_Data_ATK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Perintah ini digunakan untuk import library

import numpy as np // pustaka NumPy, digunakan untuk komputasi numerik.
import matplotlib.pyplot as plt // pustaka Matplotlib, digunakan untuk membuat grafik dan visualisasi data.
import pandas as pd // pustaka Pandas, digunakan untuk manipulasi dan analisis data.

In [83]:
dataset = pd.read_csv('ATK.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

- pd.read_csv('ReservasiHotel.csv'): Membaca file CSV bernama ATK.csv ke dalam DataFrame Pandas.
- dataset: Menyimpan data dari CSV dalam bentuk tabel.


- x: Berisi fitur (variabel independen) dari dataset.
- dataset.iloc[:, :-1]: Mengambil semua baris (:) dan semua kolom kecuali yang terakhir (:-1).
- .values: Mengubah hasilnya menjadi array NumPy.


- y: Berisi target/output (variabel dependen).
- dataset.iloc[:, -1]: Mengambil semua baris (:) dari kolom terakhir (-1).
- .values: Mengonversi ke array NumPy.


In [84]:
print(x)

[['Buku' 1.0 10000.0]
 ['Pensil' 1.0 5000.0]
 ['Spidol' 2.0 25000.0]
 ['Penggaris' 4.0 30000.0]
 ['Pulpen' 3.0 nan]
 ['Penghapus' 5.0 45000.0]
 ['Binder' 1.0 25000.0]
 ['Cutter' nan 30000.0]
 ['Gunting' 3.0 45000.0]]


Menampilkan array x

In [86]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

- from sklearn.impute import SimpleImputer

Mengimpor SimpleImputer dari pustaka sklearn.impute, yang berguna untuk mengisi nilai yang hilang dalam dataset.

- imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
Membuat objek imputer yang akan mencari nilai NaN (kosong) dalam dataset.

Parameter strategy='mean' berarti nilai yang hilang akan diganti dengan rata-rata dari kolom tersebut.

- imputer.fit(x[:, 1:3])
Melatih (fit) objek imputer pada kolom ke-1 dan ke-2 (indeks 1 dan 2 dari x).

Artinya, hanya kolom ke-1 dan ke-2 yang akan diisi dengan rata-rata (mean).

- x[:, 1:3] = imputer.transform(x[:, 1:3])
Menggunakan transform untuk menggantikan nilai kosong dalam kolom tersebut dengan rata-rata yang sudah dihitung sebelumnya.

In [87]:
print(x)

[['Buku' 1.0 10000.0]
 ['Pensil' 1.0 5000.0]
 ['Spidol' 2.0 25000.0]
 ['Penggaris' 4.0 30000.0]
 ['Pulpen' 3.0 26875.0]
 ['Penghapus' 5.0 45000.0]
 ['Binder' 1.0 25000.0]
 ['Cutter' 2.5 30000.0]
 ['Gunting' 3.0 45000.0]]


Menampilkan array x

In [88]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

- from sklearn.compose import ColumnTransformer
- from sklearn.preprocessing import OneHotEncoder

ColumnTransformer memungkinkan kita menerapkan transformasi pada kolom tertentu dari dataset.

OneHotEncoder digunakan untuk mengubah data kategorikal menjadi representasi numerik (dalam bentuk vektor biner).

- transformers=[('encoder', OneHotEncoder(sparse_output=False), [0])]

'encoder' → Nama transformer (boleh bebas, hanya sebagai identifikasi).

OneHotEncoder(sparse_output=False) → Mengubah nilai kategorikal menjadi one-hot encoding dalam bentuk array biasa (sparse_output=False agar output bukan dalam bentuk sparse matrix).

[0] → Kolom ke-0 (indeks pertama) yang akan diubah menjadi one-hot encoding.

- remainder='passthrough'

Menjaga kolom lainnya tetap ada tanpa perubahan.

- x = np.array(ct.fit_transform(x))

fit_transform(x) → Melakukan One-Hot Encoding pada kolom pertama dan mempertahankan kolom lainnya.

np.array(...) → Mengonversi hasilnya menjadi array NumPy.

In [89]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 10000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 5000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 2.0 25000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 4.0 30000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 3.0 26875.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 5.0 45000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 25000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 2.5 30000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 3.0 45000.0]]


Menampilkan array x

In [90]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

- from sklearn.preprocessing import LabelEncoder
Mengimpor LabelEncoder dari sklearn.preprocessing, yang berguna untuk mengonversi label kategorikal menjadi angka.

- le = LabelEncoder()
Membuat objek LabelEncoder untuk mengubah data target y.

- y = le.fit_transform(y)
fit_transform(y) melakukan dua hal:

Menyesuaikan encoder dengan data dalam y (memetakan kategori unik ke angka).

Mengubah setiap kategori menjadi angka yang sesuai.

In [91]:
print(y)

[1 0 1 1 0 1 0 0 1]


Menampilkan array y

In [94]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

- from sklearn.model_selection import train_test_split

Mengimpor train_test_split dari sklearn.model_selection, yang digunakan untuk membagi dataset menjadi data latih dan data uji.

-x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

x_train, y_train → Data yang digunakan untuk melatih model.

x_test, y_test → Data yang digunakan untuk mengukur performa model

In [95]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 25000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 2.5 30000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 5000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 10000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 3.0 26875.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 4.0 30000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 5.0 45000.0]]


Menampilkan array x_train

In [96]:
print (x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 3.0 45000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 2.0 25000.0]]


Menampilkan array x_test

In [98]:
print (y_train)

[0 0 0 1 0 1 1]


Menampilkan array y_train

In [99]:
print (y_test)

[1 1]


Menampilkan array y_train

In [100]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

- from sklearn.preprocessing import StandardScaler
Mengimpor StandardScaler dari sklearn.preprocessing, yang digunakan untuk menstandarisasi fitur numerik.

-sc = StandardScaler()
Membuat objek StandardScaler untuk melakukan transformasi standar pada data numerik

- x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
fit_transform(x_train[:, 3:])

fit() menghitung mean (rata-rata) dan standar deviasi dari data latih.

- x_test[:, 3:] = sc.transform(x_test[:, 3:])
Menggunakan transform() (bukan fit_transform()) pada data uji.

In [101]:
print(x_train)

[[1.0 0.0 0.0 0.0 -0.40824829046386296 -0.40824829046386296
  -0.4082482904638629 -0.40824829046386296 0.0 -1.0080322575483707
  0.03598892287471111]
 [0.0 0.0 1.0 0.0 -0.40824829046386296 -0.40824829046386296
  -0.4082482904638629 -0.40824829046386296 0.0 0.0 0.4390648590714746]
 [0.0 0.0 0.0 0.0 -0.40824829046386296 -0.40824829046386296
  2.449489742783178 -0.40824829046386296 0.0 -1.0080322575483707
  -1.5763148219123428]
 [0.0 1.0 0.0 0.0 -0.40824829046386296 -0.40824829046386296
  -0.4082482904638629 -0.40824829046386296 0.0 -1.0080322575483707
  -1.1732388857155793]
 [0.0 0.0 0.0 0.0 -0.40824829046386296 -0.40824829046386296
  -0.4082482904638629 2.4494897427831783 0.0 0.33601075251612356
  0.1871423989484974]
 [0.0 0.0 0.0 0.0 2.4494897427831783 -0.40824829046386296
  -0.4082482904638629 -0.40824829046386296 0.0 1.0080322575483707
  0.4390648590714746]
 [0.0 0.0 0.0 0.0 -0.40824829046386296 2.4494897427831783
  -0.4082482904638629 -0.40824829046386296 0.0 1.6800537625806176
  1.

Menampilkan array x_train